language: node_js

sudo: false

node_js:
  - 10
  - 9
  - 8

install:
  - npm install

script:
  - npm run test:unit
  - npm run coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
